Added Indexes and Fixed Database
Book-Recommender/backend pull request #13
Opened 2024-11-06 13:09 UTC by EdgardoJ-Gonzalez

Updated Association Table
Added Indexes
Added sqlalchemy to requirements

2024-11-08 00:27 UTC, jonathan-d-zhang requested changes
Schema looks good overall, just some minor changes to align with best practices.

2024-11-08 00:27 UTC, jonathan-d-zhang commented on src/openbook/models.py
> +    book_id = Column(Integer, ForeignKey("books.id"), primary_key=True)
We should use the declarative form when possible: reduces boilerplate and adds type hints.

https://docs.sqlalchemy.org/en/20/orm/declarative_tables.html#declarative-table-with-mapped-column

2024-11-08 00:27 UTC, jonathan-d-zhang commented on src/openbook/models.py
>  Base = declarative_base()
```suggestion
from sqlalchemy.orm import MappedAsDataclass, DeclarativeBase
class Base(MappedAsDataclass, DeclarativeBase, kw_only=True):
    pass
```

2024-11-08 00:27 UTC, jonathan-d-zhang commented on src/openbook/models.py
> +    user_id = Column(Integer, ForeignKey("users.id"), primary_key=True)
Are we sure that having two columns with `primary_key=True` creates a composite primary key? I also see that you have the `__table_args__` below... I don't think we need the kwarg and the table arg.

2024-11-08 00:27 UTC, jonathan-d-zhang commented on src/openbook/models.py
> +    __tablename__ = "user_book"
Be consistent in the table name: either all plural (`users_books`), or don't make the user table plural (`user`). Same with `books`.

2024-11-08 00:27 UTC, jonathan-d-zhang commented on src/openbook/models.py
> +    user_book_entries = relationship("UserBook", back_populates="user")
```suggestion
    books = relationship("UserBook", back_populates="user")
```

2024-11-08 00:27 UTC, jonathan-d-zhang commented on src/openbook/models.py
> +    user_book_entries = relationship("UserBook", back_populates="book")
```suggestion
    users = relationship("UserBook", back_populates="book")
```

2024-11-09 00:01 UTC, jonathan-d-zhang submitted a review, later dismissed
Minor nits. Looks good though

2024-11-09 00:07 UTC, EdgardoJ-Gonzalez commented on src/openbook/models.py
> +    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
Do you want me to remove this from all of them due to the type hints?

2024-11-09 00:10 UTC, EdgardoJ-Gonzalez commented on src/openbook/models.py
> +    # Many-to-many relationship with Author through AuthorBook with type hints
Why remove the comments?

2024-11-09 01:10 UTC, jonathan-d-zhang commented on src/openbook/models.py
> +    # Many-to-many relationship with Author through AuthorBook with type hints
Redundant

2024-11-09 01:11 UTC, jonathan-d-zhang commented on src/openbook/models.py
> +    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
That would be appreciated.

2024-11-09 14:45 UTC, jonathan-d-zhang approved these changes
:shipit:

2024-11-09 14:45 UTC, merged